table Dim_Date
	lineageTag: e7e768bf-9a57-4967-ae79-2968f8b84cb5
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 1f5d1c72-7f08-4c09-86ae-4a4983879fef
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 29df7e09-7f5d-499b-9a10-440eff608bef
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: string
		lineageTag: 36f7cd08-6d1b-41eb-84d9-690e23fcd811
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthNum

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: c7d38a8c-5e73-42f9-8298-fd8c4f49ff30
		summarizeBy: none
		sourceColumn: MonthNum

	column YearMonth
		dataType: string
		lineageTag: af8c8a0b-ac67-4887-b9be-aebdc5a03ffb
		summarizeBy: none
		sourceColumn: YearMonth

	column MonthYearKey
		dataType: int64
		formatString: 0
		lineageTag: e7df6996-204e-4e07-aaa9-06fafa7bbb8a
		summarizeBy: none
		sourceColumn: MonthYearKey

	partition Dim_Date = m
		mode: import
		source =
				let
					Source = List.Dates(#date(2020, 1, 1), 2556, #duration(1, 0, 0, 0)),
					#"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
					#"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{ {"Date", type date} }),
					#"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
					#"Inserted MonthNum" = Table.AddColumn(#"Inserted Year", "MonthNum", each Date.Month([Date]), Int64.Type),
					#"Inserted MonthName" = Table.AddColumn(#"Inserted MonthNum", "MonthName", each Date.ToText([Date], "MMM"), type text),
					#"Upper Month" = Table.TransformColumns(#"Inserted MonthName", { {"MonthName", Text.Upper} }),
					#"Renamed Month" = Table.RenameColumns(#"Upper Month", { {"MonthName", "Month"} }),
					#"Inserted YearMonth" = Table.AddColumn(#"Renamed Month", "YearMonth", each Text.From([Year]) & "-" & [Month], type text),
					#"Inserted MonthYearKey" = Table.AddColumn(#"Inserted YearMonth", "MonthYearKey", each [Year] * 100 + [MonthNum], Int64.Type)
				in
					#"Inserted MonthYearKey"

