table Dim_Product
	lineageTag: 986810f5-ef55-4c27-aece-dd081cf0d23f

	column Product
		dataType: string
		isKey
		lineageTag: b7766cf3-2e61-4704-80d0-a6fb1fdf81a4
		summarizeBy: none
		sourceColumn: Product

	column Subcategory
		dataType: string
		lineageTag: 39af529e-c042-4415-a4d7-5cb822ed812c
		summarizeBy: none
		sourceColumn: Subcategory

	column Category
		dataType: string
		lineageTag: 3254d6c1-4f88-4538-9e49-065fc6f35995
		summarizeBy: none
		sourceColumn: Category

	column 'Packaging Unit'
		dataType: string
		lineageTag: e49f9869-7114-4891-b843-536643103983
		summarizeBy: none
		sourceColumn: Packaging Unit

	partition Dim_Product = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents(SourceFilePath), null, true),
					Database_Sheet = Source{[Item="Database",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Database_Sheet, [PromoteAllScalars=true]),
					#"Trimmed Text" = Table.TransformColumns(#"Promoted Headers", { {"Category", Text.Trim}, {"Product", Text.Trim} }),
					#"Added Subcategory" = Table.AddColumn(#"Trimmed Text", "Subcategory", each if [Product] <> null and Text.Contains(Text.Lower(Text.From([Product])), "water") then "Water" else if [Product] <> null and Text.Contains(Text.Lower(Text.From([Product])), "coke") then "Soda" else "Other", type text),
					#"Select Columns" = Table.SelectColumns(#"Added Subcategory", {"Product", "Subcategory", "Category", "Packaging Unit"}),
					#"Distinct Products" = Table.Distinct(#"Select Columns"),
					#"Filtered Blanks" = Table.SelectRows(#"Distinct Products", each [Product] <> null and Text.Trim(Text.From([Product])) <> "")
				in
					#"Filtered Blanks"

