table Fact_Demand
	lineageTag: 8e730ffc-86a9-4ec3-9325-2b56c152c48e

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2145b7f3-a424-41e3-9beb-eb10b96b508d
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: string
		lineageTag: e885748d-9bb6-4ece-a357-8ce0b11dde1e
		summarizeBy: none
		sourceColumn: Month

	column Category
		dataType: string
		lineageTag: 6ae323c1-f82d-4c82-8f11-9bf87f592a8d
		summarizeBy: none
		sourceColumn: Category

	column Product
		dataType: string
		lineageTag: 658a6d41-5787-4c92-8ff4-77a07e6b4d46
		summarizeBy: none
		sourceColumn: Product

	column Subcategory
		dataType: string
		lineageTag: b3fa52ea-bca2-4ed5-ac74-beef40bcf469
		summarizeBy: none
		sourceColumn: Subcategory

	column 'Packaging Unit'
		dataType: string
		lineageTag: 7ff310fa-5875-46eb-96ec-e07a3beed264
		summarizeBy: none
		sourceColumn: Packaging Unit

	column Forecast
		dataType: int64
		formatString: #,0
		lineageTag: 8b18b3ee-000a-4e2d-b4bb-853f51bc9e6a
		summarizeBy: sum
		sourceColumn: Forecast

	column Sales
		dataType: double
		formatString: #,0
		lineageTag: f97196fe-6ff2-4dcd-945e-528ca4ed4ac4
		summarizeBy: sum
		sourceColumn: Sales

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: 3690940f-2a51-4aac-acfa-85bfe282d783
		summarizeBy: none
		sourceColumn: MonthNum

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ddbe291e-fcd6-4068-8b53-8e35537ee44e
		summarizeBy: none
		sourceColumn: Date

	column MonthYearKey
		dataType: int64
		formatString: 0
		lineageTag: c41e5155-b80c-4be1-afc6-046dbd956128
		summarizeBy: none
		sourceColumn: MonthYearKey

	partition Fact_Demand = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents("C:\Users\bucay\OneDrive\Documents\Fede\AI Test\Demand Planning\Forecasting_&_Actuals_Database.xlsx"), null, true),
					Database_Sheet = Source{[Item="Database",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Database_Sheet, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{ {"Year", Int64.Type}, {"Month", type text}, {"Category", type text}, {"Product", type text}, {"Packaging Unit", type text}, {"Forecast", Int64.Type}, {"Sales", type number} }),
					#"Trimmed Text" = Table.TransformColumns(#"Changed Type", { {"Month", Text.Trim}, {"Category", Text.Trim}, {"Product", Text.Trim} }),
					#"Upper Month" = Table.TransformColumns(#"Trimmed Text", { {"Month", Text.Upper} }),
					#"Added Subcategory" = Table.AddColumn(#"Upper Month", "Subcategory", each if [Product] <> null and Text.Contains(Text.Lower(Text.From([Product])), "water") then "Water" else if [Product] <> null and Text.Contains(Text.Lower(Text.From([Product])), "coke") then "Soda" else "Other", type text),
					#"Added MonthNum" = Table.AddColumn(#"Added Subcategory", "MonthNum", each if [Month] = "JAN" then 1 else if [Month] = "FEB" then 2 else if [Month] = "MAR" then 3 else if [Month] = "APR" then 4 else if [Month] = "MAY" then 5 else if [Month] = "JUN" then 6 else if [Month] = "JUL" then 7 else if [Month] = "AUG" then 8 else if [Month] = "SEP" then 9 else if [Month] = "OCT" then 10 else if [Month] = "NOV" then 11 else if [Month] = "DEC" then 12 else 99, Int64.Type),
					#"Added Date" = Table.AddColumn(#"Added MonthNum", "Date", each #date([Year], [MonthNum], 1), type date),
					#"Added MonthYearKey" = Table.AddColumn(#"Added Date", "MonthYearKey", each [Year] * 100 + [MonthNum], Int64.Type),
					#"Filtered Blanks" = Table.SelectRows(#"Added MonthYearKey", each [Product] <> null and Text.Trim(Text.From([Product])) <> "")
				in
					#"Filtered Blanks"

