table Fact_Demand
	lineageTag: 01b47632-8e69-4fb4-b1d1-d3e8ee14cfc3

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 823a6d6b-e12c-4196-9808-6ae16075f4ac
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: string
		lineageTag: ec701979-f9b8-4452-adc9-2e3f5d32509f
		summarizeBy: none
		sourceColumn: Month

	column Category
		dataType: string
		lineageTag: d180cc6c-ac54-4e2c-a4bb-c6d1a58b3081
		summarizeBy: none
		sourceColumn: Category

	column Product
		dataType: string
		lineageTag: cfcb6823-0fa3-4007-b168-fb135c3108e3
		summarizeBy: none
		sourceColumn: Product

	column Subcategory
		dataType: string
		lineageTag: 2c043ca3-a82e-46ec-9f5c-859bc959aa0b
		summarizeBy: none
		sourceColumn: Subcategory

	column 'Packaging Unit'
		dataType: string
		lineageTag: fdc92877-81a8-41b3-aa43-e845927a9c45
		summarizeBy: none
		sourceColumn: Packaging Unit

	column Forecast
		dataType: int64
		formatString: #,0
		lineageTag: 63583e17-aa95-462a-9a1b-1edc2f630bb8
		summarizeBy: sum
		sourceColumn: Forecast

	column Sales
		dataType: double
		formatString: #,0
		lineageTag: 32418078-7027-41ea-bd2b-309bc8ff98da
		summarizeBy: sum
		sourceColumn: Sales

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: 8a7d9f0f-afd0-421e-bfd4-862747f0539f
		summarizeBy: none
		sourceColumn: MonthNum

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: adb00683-c89f-4ad5-8c74-9d474cd780ef
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column MonthYearKey
		dataType: int64
		formatString: 0
		lineageTag: 2a8a50c5-71d5-4c76-97e3-4817d347faac
		summarizeBy: none
		sourceColumn: MonthYearKey

	column Column8
		dataType: string
		lineageTag: 7655b191-865a-4d15-9b22-3c860db63399
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 5e30bc26-277b-4f1f-9cf8-f292fbc9d806
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 16e67c16-5e26-4627-9d0d-61a25ea555dc
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: c3fb8f57-2fd2-4396-b77d-9c9fb9b1eda6
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 15450ae3-0d40-4092-802a-19d8727accbf
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: ea742de4-2868-48ac-95d3-4130ec5d1fcf
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: b141366a-c0ac-4c14-8977-ba3ced331370
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 24eb16e5-03cd-4fb1-ad92-608fa49ee5bc
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	partition Fact_Demand = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents(SourceFilePath), null, true),
					Database_Sheet = Source{[Item="Database",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Database_Sheet, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{ {"Year", Int64.Type}, {"Month", type text}, {"Category", type text}, {"Product", type text}, {"Packaging Unit", type text}, {"Forecast", Int64.Type}, {"Sales", type number} }),
					#"Trimmed Text" = Table.TransformColumns(#"Changed Type", { {"Month", Text.Trim}, {"Category", Text.Trim}, {"Product", Text.Trim} }),
					#"Upper Month" = Table.TransformColumns(#"Trimmed Text", { {"Month", Text.Upper} }),
					#"Added Subcategory" = Table.AddColumn(#"Upper Month", "Subcategory", each if [Product] <> null and Text.Contains(Text.Lower(Text.From([Product])), "water") then "Water" else if [Product] <> null and Text.Contains(Text.Lower(Text.From([Product])), "coke") then "Soda" else "Other", type text),
					#"Added MonthNum" = Table.AddColumn(#"Added Subcategory", "MonthNum", each if [Month] = "JAN" then 1 else if [Month] = "FEB" then 2 else if [Month] = "MAR" then 3 else if [Month] = "APR" then 4 else if [Month] = "MAY" then 5 else if [Month] = "JUN" then 6 else if [Month] = "JUL" then 7 else if [Month] = "AUG" then 8 else if [Month] = "SEP" then 9 else if [Month] = "OCT" then 10 else if [Month] = "NOV" then 11 else if [Month] = "DEC" then 12 else 99, Int64.Type),
					#"Added Date" = Table.AddColumn(#"Added MonthNum", "Date", each #date([Year], [MonthNum], 1), type date),
					#"Added MonthYearKey" = Table.AddColumn(#"Added Date", "MonthYearKey", each [Year] * 100 + [MonthNum], Int64.Type),
					#"Filtered Blanks" = Table.SelectRows(#"Added MonthYearKey", each [Product] <> null and Text.Trim(Text.From([Product])) <> "")
				in
					#"Filtered Blanks"

